export const managementStaff = [
  {
    name: "Kamil",
    appointment: "CEO",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Kewin",
    appointment: "CTO",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Dominika",
    appointment: "Head of HR",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Natalia",
    appointment: "Head of Design",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Oliwer",
    appointment: "Business Partner",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Damian",
    appointment: "Business Partner",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
  {
    name: "Maciej",
    appointment: "Business Partner",
    instagramUrl: "https://www.instagram.com/",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://twitter.com/",
    linkedinUrl: "https://www.linkedin.com/",
    dribbbleUrl: "https://dribbble.com/",
    behanceUrl: "https://www.behance.net/",
    githubUrl: "https://github.com/",
  },
];
